---
- name: Reset passwords for all users except specific ones
  hosts: win
  tasks:
    - name: execute batch
      script: /tmp/run.bat
      register: out

    - debug: var=out.stdout_lines