# to run use sudo ansible-playbook -i inventory alpine.yml
# add vm name, ip, and root pass (for both password fields) in inventory file
# add path to save file to in the last task
- name: Enumerate Alpine servers
  hosts: alpine_servers
  become: yes
  tasks:
    
    - name: Get list of active services running
      command: "sudo rc-status"
      register: services_run
      ignore_errors: yes
      failed_when: services_run.rc != 0 and services_run.rc != 1
    
    - name: Check if netstat is installed
      command: which netstat
      register: netstat_check
      ignore_errors: yes
      failed_when: netstat_check.rc != 0 and netstat_check.rc != 1


    - name: Get tcp, udp, pid, addy + port for listening ports
      when: netstat_check.rc == 0
      command: "netstat -tulnp" # ss -tuln
      register: ports_all
      ignore_errors: yes
      failed_when: ports_all.rc != 0 and ports_all.rc != 1

    - name: connections, addresses/ports, tcp, udp, pid, and unix domain sockets
      when: netstat_check.rc == 0
      command: "netstat -antupx"
      register: connections
      ignore_errors: yes
      failed_when: connections.rc != 0 and connections.rc != 1

    - name: Get distro and version
      shell: "cat /etc/*-release"
      register: distro_version
      ignore_errors: yes
      failed_when: distro_version.rc != 0 and distro_version.rc != 1

    - name: Get kernel version
      command: "cat /proc/version"
      register: kernel_version
      ignore_errors: yes
      failed_when: kernel_version.rc != 0 and kernel_version.rc != 1

    - name: Get running processes
      command: "ps aux"
      register: processes
      ignore_errors: yes
      failed_when: processes.rc != 0 and processes.rc != 1
    
    - name: root proceses
      shell: "ps aux | grep root"
      register: root_processes
      ignore_errors: yes
      failed_when: root_processes.rc != 0 and root_processes.rc != 1

    - name: Get installed apps/packages, versions, and if they are running 
      command: "apk info"
      register: alpine_packages
      ignore_errors: yes
      failed_when: alpine_packages.rc != 0 and alpine_packages.rc != 1

    - name: individual cron jobs
      shell: "cat /etc/cron.d/*"
      register: cron_jobs_individual
      ignore_errors: yes
      failed_when: cron_jobs_individual.rc != 0 and cron_jobs_individual.rc != 1
    
    - name: Daily cron jobs
      shell: "cat /etc/cron.daily/*"
      register: daily_cron_jobs
      ignore_errors: yes
      failed_when: daily_cron_jobs.rc != 0 and daily_cron_jobs.rc != 1

    - name: Hourly cron jobs
      shell: "cat /etc/cron.hourly/*"
      register: hourly_cron_jobs
      ignore_errors: yes
      failed_when: hourly_cron_jobs.rc != 0 and hourly_cron_jobs.rc != 1

    - name: Weekly cron jobs
      shell: "cat /etc/cron.weekly/*"
      register: weekly_cron_jobs
      ignore_errors: yes
      failed_when: weekly_cron_jobs.rc != 0 and weekly_cron_jobs.rc != 1

    - name: Monthly cron jobs
      shell: "cat /etc/cron.monthly/*"
      register: monthly_cron_jobs
      ignore_errors: yes
      failed_when: monthly_cron_jobs.rc != 0 and monthly_cron_jobs.rc != 1
    
    - name: System wide cron jobs
      command: "cat /etc/crontab"
      register: system_cron_jobs
      ignore_errors: yes
      failed_when: system_cron_jobs.rc != 0 and system_cron_jobs.rc != 1

    - name: Get anacron jobs (cron jobs that do not require system to be running)
      command: "cat /etc/anacrontab"
      register: anacron_jobs
      ignore_errors: yes
      failed_when: anacron_jobs.rc != 0 and anacron_jobs.rc != 1

    - name: Active interfaces (including inactive/down), Ip address, MAC, netmask, broadcast, and more
      command: "ifconfig -a"
      register: ifconfig_interfaces
      ignore_errors: yes
      failed_when: ifconfig_interfaces.rc != 0 and ifconfig_interfaces.rc != 1

    - name: check if ip installed
      command: which ip
      register: ip_check
      ignore_errors: yes
      failed_when: ip_check.rc != 0 and ip_check.rc != 1

    - name : links/network interfaces
      when: ip_check.rc == 0
      command: ip link
      register: connected_interfaces
      ignore_errors: yes
      failed_when: connected_interfaces.rc != 0 and connected_interfaces.rc != 1

    - name: Network interface configurtion
      command: "cat /etc/network/interfaces"
      register: alpine_interfaces
      ignore_errors: yes
      failed_when: alpine_interfaces.rc != 0 and alpine_interfaces.rc != 1

    - name: files + processes related to internet/network connections
      command: "lsof -i"
      register: network_files_processes
      ignore_errors: yes
      failed_when: network_files_processes.rc != 0 and network_files_processes.rc != 1

    - name: files + processes but only port 80
      command: "lsof -i :80"
      register: port_80_files_processes
      ignore_errors: yes
      failed_when: port_80_files_processes.rc != 0 and port_80_files_processes.rc != 1

    - name: user login history
      command: "last"
      register: login_history
      ignore_errors: yes
      failed_when: login_history.rc != 0 and login_history.rc != 1

    - name: sudoers file/permissions
      command: "cat /etc/sudoers"
      register: sudoers
      ignore_errors: yes
      failed_when: sudoers.rc != 0 and sudoers.rc != 1

    - name: files and directories/subdirectories in /root/ dir
      command: "ls -ahlR /root/"
      register: root_files
      ignore_errors: yes
      failed_when: root_files.rc != 0 and root_files.rc != 1

    - name: bash histroy
      command: "cat ~/.ash_history"
      register: ash_history
      ignore_errors: yes
      failed_when: ash_history.rc != 0 and ash_history.rc != 1

    - name: ssh keys
      command: "cat ~/.ssh/*" # check other dirs
      register: ssh_keys
      ignore_errors: yes
      failed_when: ssh_keys.rc != 0 and ssh_keys.rc != 1

    - name: mounted filesystems
      command: "mount"
      register: mounted_filesystems
      ignore_errors: yes
      failed_when: mounted_filesystems.rc != 0 and mounted_filesystems.rc != 1
    
    - name: disk space usage for mounted filesystems
      command: "df -h"
      register: disk_space
      ignore_errors: yes
      failed_when: disk_space.rc != 0 and disk_space.rc != 1

    - name: detect unmounted file-systems
      command: "cat /etc/fstab"
      register: unmounted_filesystems
      ignore_errors: yes
      failed_when: unmounted_filesystems.rc != 0 and unmounted_filesystems.rc != 1

    - name: world writable folders
      shell: "find / -xdev -type d -perm -0002 -ls 2>/dev/null"
      register: world_writable_folders
      failed_when: world_writable_folders.rc != 0 and world_writable_folders.rc !=1

    - name: world writable files
      shell: "find / -xdev -type f -perm -0002 -ls 2>/dev/null"
      register: world_writable_files
      failed_when: world_writable_files.rc != 0 and world_writable_files.rc != 1

    - name: prepare consolidated output
      set_fact:
        consolidated_output:  |
          Active Services:
          {{ services_run.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Listening ports:
          {{ ports_all.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Connections, addresses/ports, tcp, udp, pid, and unix domain sockets:
          {{ connections.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Versions and distro:
          {{ distro_version.stdout | default('') }} 
          ------------------------------------------
          ------------------------------------------
          Kernel version: 
          {{ kernel_version.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          All processes:
          {{ processes.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Root processes:
          {{ root_processes.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Installed packages:
          {{ alpine_packages.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Individual cron jobs:
          {{ cron_jobs_individual.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Daily cron jobs:
          {{ daily_cron_jobs.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Hourly cron jobs:
          {{ hourly_cron_jobs.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Weekly cron jobs:
          {{ weekly_cron_jobs.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Monthly cron jobs:
          {{ monthly_cron_jobs.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          System wide cron jobs:
          {{ system_cron_jobs.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Anacron jobs:
          {{ anacron_jobs.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Active interfaces:
          {{ ifconfig_interfaces.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Connected interfaces:
          {{ connected_interfaces.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Network interface configuration:
          {{ alpine_interfaces.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          All files and processes related to network connections:
          {{ network_files_processes.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Files and processes related to port 80:
          {{ port_80_files_processes.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Login history:
          {{ login_history.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Sudoers file:
          {{ sudoers.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Files and directories in /root/:
          {{ root_files.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Bash history:
          {{ ash_history.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          SSH keys:
          {{ ssh_keys.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Mounted filesystems:
          {{ mounted_filesystems.stdout | default('')  }}
          ------------------------------------------
          ------------------------------------------

          Disk space usage:
          {{ disk_space.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          Unmounted filesystems:
          {{ unmounted_filesystems.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          World writable folders:
          {{ world_writable_folders.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

          World writable files:
          {{ world_writable_files.stdout | default('') }}
          ------------------------------------------
          ------------------------------------------

    - name: Write consolidated output to file
      copy:
        content: "{{ consolidated_output }}"
        dest: "/wrccdc/enumeration/alpine_enum/{{ inventory_hostname }}-consolidated-output.txt" #change to where you want to save file
        mode: '0777'
      delegate_to: localhost