# to run use sudo ansible-playbook -i inventory change_root.yml
# add vm name, ip, and root pass (for both password fields) in inventory file
# add path to save file to in the last task
- name: Change root password on Linux servers
  hosts: linux_servers
  become: yes
  vars:
     root_user: root
  tasks:

    - name: Define password file name
      set_fact:
        password_file: "new_root_pass.txt"

    - name: Generate a new password for root user
      set_fact:
        # root_password is ansible var to store pass
        # lookup() generates random pass w/length 16 using ascii letters, digs, + punct
        root_password: "{{ lookup('password', '/dev/null', length=16, chars='ascii_letters,digits,punctuation') }}"
      
    - name: Change password for root user
      # user is ansible module to manage user accounts
      user:
        # sets root user
        name: "{{ root_user }}"
        # retrieves new root password + hashes w/ sha512
        password: "{{ root_password | password_hash('sha512') }}"
    
    - name: Print the new root password
      debug:
        msg: "New root password: {{ root_password }}"

    #
    - name: Save new password to file
      copy:
        content: "New root password: {{ root_password }}"
        dest: "/wrccdc/root_pass/{{ inventory_hostname }}-{{ password_file }}" #change to where you want to save file
        mode: '0777'  
      delegate_to: localhost 


